"""Initial migration

Revision ID: d3e73d5ab8a4
Revises: 
Create Date: 2025-09-30 16:03:35.674821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e73d5ab8a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('hoteis')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=40), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('senha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('value',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    op.create_table('hoteis',
    sa.Column('hotel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('estrelas', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('diaria', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('hotel_id', name=op.f('hoteis_pkey'))
    )
    op.create_table('usuarios',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('senha', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('usuarios_pkey'))
    )
    # ### end Alembic commands ###
